name: pspc
channels:
  - pytorch
  - nvidia
dependencies:
  - python>=3.8, < 3.10  # package build failures on 3.10
  - pip
  - numpy=1.24.3
  - click>=8.0
  - pillow>=8.3.1
  - scipy>=1.7.1
  - pytorch=2.1.0
  - psutil
  - requests
  - tqdm
  - imageio
  - matplotlib
  - pip:
    - imageio-ffmpeg>=0.4.3
    - pyspng
